### ISSUE TITLE
Semicolon included in data types

### ISSUE THREAD

**Issue by peterkarman1** [devshop/typescript-interface-to-builder-class#1]
Thanks for this extension! It's great!
There's an issue with it when your properties include a semicolon at the end of the line as such

![image](https://user-images.githubusercontent.com/9062217/60185519-12868480-97f8-11e9-95e3-6fea1e130faf.png)

The semi colon gets included as such

![image](https://user-images.githubusercontent.com/9062217/60185559-25995480-97f8-11e9-96b8-ff084a626066.png)

I tried to push up a branch with a fix to do a pr but couldn't due to access issues. Here's the fix
change regex to (?<=:\s)(.*)[^;]+   

![image](https://user-images.githubusercontent.com/9062217/60185623-3ea20580-97f8-11e9-83bc-5fbb72cd2728.png)

**Comment by devshop** [comment]
@peterkarman1 Thanks for the feedback! Sorry about the PR access issues. I'm not sure what settings I need to change. I have added support for semicolons in both the interface and the builder. Please let me know if you find any other issues. If you update the extension in VS Code to 0.1.4 you should see the changes.
