### ISSUE TITLE
Extract builder generator into a project that can be run without vscode

### ISSUE THREAD

**Issue by etler** [devshop/typescript-interface-to-builder-class#13]
Is there a command line or node module version of this project? I would love to use this as an automated build step so I can keep these files up to date automatically, and if the builder class generator were to be extracted into a dependency I could set it up to create the files automatically.

**Comment by devshop** [comment]
@etler no, I built this purely as a vscode extension to save myself time. Feel free to borrow whatever you need if you want to make it run on the command line.

**Comment by etler** [comment]
Thanks! I'll make sure to link back and credit you if I do.
