### ISSUE TITLE
Always failing with "Could not find any properties defined in the interface."

### ISSUE THREAD

**Issue by manwithsteelnerves** [devshop/typescript-interface-to-builder-class#8]
I tried the extension but unfortunately its not working as expected.
When ever i try to generate from command palette, it fails with "Could not find any properties defined in the interface." message.

Anything I'm missing?

**Comment by manwithsteelnerves** [comment]
Ok, I find out the problem is with the regular expression when searching for properties.

```
  const properties = text.match(/(\w*[^\s])(?=:)/gm)
```
[code snippet](https://github.com/devshop/typescript-interface-to-builder-class/blob/2aa9fbb2e314a66e3766d7306afe97e8a4484574/src/utils/interface-properties-util.ts#L12)

I would suggest it to change it to below regex to accommodate custom formatting.

```
  const properties = text.match(/(\w*[^\s][ \t]*)(?=:)/gm)
```

**Comment by devshop** [comment]
@manwithsteelnerves Can you please paste an example of one of your interfaces? I’m interested in how they differ from my interfaces.

**Comment by manwithsteelnerves** [comment]
```
export interface IUser {
firstName      : string; //Updated
lastName       : string;//Updated
}
```

**Comment by devshop** [comment]
@manwithsteelnerves Is the issue happening because you have a comma in your interface? The properties should end in a semicolon, or nothing.

**Comment by manwithsteelnerves** [comment]
Hey Sorry,
It's a typo. I just updated. Its failing as there are spaces next to the parameters before :

**Comment by devshop** [comment]
@manwithsteelnerves I have updated the extension. Make sure it is version 0.1.9 and give it a try. Please let me know if you have any issues.
